#include "expander.h"

/*
The order of word expansion shall be as follows:
Tilde expansion, parameter expansion, command substitution, and arithmetic expansion shall be performed, beginning to end.
Field splitting (see Field Splitting) shall be performed on the portions of the fields generated by step 1, unless IFS is null.
Pathname expansion (see Pathname Expansion) shall be performed, unless set -f is in effect.
Quote removal (see Quote Removal) shall always be performed last.

In minishell, following procedure is required:
Parameter expansion.
Field splitting.
Quote removal.
*/

/*
void print_tree2(t_node *cur)
{
	t_cmd_node *tmp;

	if (cur->left)
		print_tree2(cur->left);
	if (cur->kind != ND_PIPE)
	{
		tmp = cur->cmd;
		while (tmp)
		{
			if (tmp->next)
				printf("node: %s\n", tmp->str);
			else
				printf("node: %s", tmp->str);
			tmp = tmp->next;
		}
	}
	else
	{
		printf("node: %s", cur->str);
	}
	printf("\n");
	if (cur->right)
		print_tree2(cur->right);
}
*/

t_node *expand(t_node *root)
{
	// printf("---- param ----\n");
	expand_params(root);
	// system("leaks -q minishell");
	// printf("----  end  ----\n");
	// printf("---- split ----\n");
	split_field(root);
	// system("leaks -q minishell");
	// print_tree2(root);
	// printf("----  end  ----\n");
	// printf("---- remove ----\n");
	remove_quote(root);
	// system("leaks -q minishell");
	// printf("----  end  ----\n");
	return (root);
}